'import pytest' 
'from main import StudentsInMLOps' 
'' 
'def test_enrollStudents():' 
'    ml_ops = StudentsInMLOps()' 
'    ml_ops.enrollStudents(10)' 
'    assert ml_ops.getTotalStrength() == 10' 
'' 
'def test_dropStudents():' 
'    ml_ops = StudentsInMLOps()' 
'    ml_ops.enrollStudents(10)' 
'    ml_ops.dropStudents(5)' 
'    assert ml_ops.getTotalStrength() == 5' 
